---
title: Arsha
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
  client-logo:
    title: client-logo
    output: true
  services:
    title: services
    output: true
email: viraj.chaudharyAapexure.com
description: website using html css bootstap jekyll git and siteleaf
baseurl: "/arsha"
url: https://virajchuaudhary.github.io
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
